prometheus:
  endpoint_port: 8080
api:
  port: 8085
cost:
  enabled: true
  sources:
    energy:
      strategy: solar_energy
      min_cost: -0.05
      max_cost: 0.3
      peak_time: 43200
      period: 86400
    cloud:
      strategy: cloud
      min_cost: 100.0
      max_cost: 500.0
      peak_time: 21600
      period: 86400
